LLAMA_API_KEY = "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"
LLAMA_MODEL = "llama3-70b-8192"

NEO4J_URI = "bolt://localhost:7687"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = "Neo4jpassword"

MYSQL_HOST = "localhost"
MYSQL_USER= "root"
MYSQL_PASSWORD = "Wealth3visual%"
MYSQL_DB = "set50"